app:
  home: SELTEST_HOME

server:
  port: 8011

spring:
  datasource:
    ###### PostgreSQL Configuration #######
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/seltest_master
    username: mdzahidraza
    password: zahid
    platform: postgresql
    host: localhost
    port: 5432
    masterdb: mtdbapp_master

  jpa:
    show-sql: false
    format-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    protocol: smtp
    test-connection: false
    host: mail.privateemail.com
    port: 587
    username: noreply@jaza-soft.com
    password: Jaza@7292
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

liquibase:
  enabled: true
  rollback-file: '/Users/mdzahidraza/projects/local-repo/sel-test/src/main/resources/changelog/master/rollback-sql-temp.sql'


